### ISSUE TITLE
Stuck on PokemonGo - DEBUG - Return code 0

### ISSUE THREAD

**Issue by calum2255** [Azelphur/PokemonGo-CalcyIV-Renamer#9]
Not sure if I'm missing something but I've plugged in my S9 plus and opened pokemon go but I get stuck at this stage and nothing is happening, is this a bug or have I missed something?

```
λ python ivcheck.py
2018-10-15 21:35:36,312 - PokemonGo - DEBUG - Running ['adb', 'devices']
2018-10-15 21:35:36,428 - PokemonGo - DEBUG - Return code 0
2018-10-15 21:35:36,429 - PokemonGo - DEBUG - Starting logcat ['adb', '-s', '1a50144cdb0b7ece', 'logcat', '-T', '1', '-v', 'brief']
2018-10-15 21:35:36,634 - PokemonGo - DEBUG - Running ['adb', '-s', '1a50144cdb0b7ece', 'shell', 'am broadcast intent:#Intent\\;action=tesmath.calcy.ACTION_ANALYZE_SCREEN\\;B.silentMode=true\\;end -n tesmath.calcy/.IntentReceiver']
2018-10-15 21:35:36,802 - PokemonGo - DEBUG - Return code 0
```

Many thanks
Calum

**Comment by Azelphur** [comment]
I don't think Calcy IV has updated for the CP reshuffle yet, so I doubt things will work until then?

**Comment by Azelphur** [comment]
Actually looks like the IV changes got reverted, can you test again and let me know if the issue is still effecting you?

**Comment by LasseSLambertsen** [comment]
Not working with latest calcyiv and commit :)
Still OP's error

**Comment by Azelphur** [comment]
That's interesting, can you confirm that calcy IV is running? the only time I've seen this issue is if Calcy IV isn't running.

**Comment by LasseSLambertsen** [comment]
It's running alright, can use it manually just fine :)

**Comment by Azelphur** [comment]
That's strange - it works on my phone.

I've added a debug line to my code to try and diagnose this - can you rerun and post a new log?

**Comment by LasseSLambertsen** [comment]
Just ran it, noticing this line:

`Background execution not allowed: receiving Intent { act=tesmath.calcy.ACTION_ANALYZE_SCREEN flg=0x400010 (has extras) } to tesmath.calcy/.IntentReceiver`

**Comment by Azelphur** [comment]
Interesting, seems like some security issue that doesn't effect my phone.
Could you try running `adb shell am broadcast -a tesmath.calcy.ACTION_ANALYZE_SCREEN -n tesmath.calcy/.IntentReceiver --ez silentMode true` and tell me if it works on your phone?

If it works:
- The calcy IV button will flicker briefly, however the appraisal DIALOG will not appear (calcyIV is being ran in silent mode)
- Calcy IV will have set the clipboard

If it doesn't work:
That error will appear (possibly only in logcat)

**Comment by LasseSLambertsen** [comment]
That command works :)

**Comment by LasseSLambertsen** [comment]
Working perfectly now! :)
Great work man!

**Comment by Azelphur** [comment]
Np, thanks for your help! :)

**Comment by Caprikey** [comment]
I was also running into the same issue with my Samsung S9+. I haven't tested your updated code yet... 

However, prior when I attempted the ADB broadcast command it didn't seem like Calcy was performing the scan. If I ran your code set from last night and manually pressed the Calcy 'Coin' button to perform the scan, the code would then automate like it should to rename my pokemon. However, it would hang on Closing Calcy and would not perform the swipe command to go to the next pokemon. 

So... playing around, i  ended up getting the Close Calcy function to work by changing "if values["success"] is False" from "if values["success"] is True: "  inside the Class.main async def start(self): in IVCheck.py... This was most likely an error on my part by not realizing I needed to pass in to the --touch-paste arguments... The next hang up was towards the end... It would not close the rename box... I believe I had to swap my "Rename_Ok" and "Keyboard_Ok" to get it to work... However, i forgot to make note of which of the two I swapped... Again.. this is probably what I had to do to get it to work since I didn't know about the Arguments that I needed to pass through until I looked at it again both today and later on... So it may be worth it adding a section to your readme about the different arguments you have coded in and when/why to use them... 

After that...the only problem was that the script would then not perform the swipe to the next Pokemon part... I also was not sure where I was supposed to put the swipe locations into the script/config file either... I didn't see a section for the x1y1 x2y2 locations in the Config file but did see the locations placed in the other files... However upon further review now, it looks like I was once again making a mistake on my part... I believe that your swipe function was for changing pokemon.. but it appears that i needed to locate that 'sweet' spot on the screen that will cause it to go to the next pokemon by a tap and not through the use of a swipe... Totally my confusion because I believed only swiping would perform the change... I had done a similar script like this myself but in CMD Batch sending ADB and I had used the adb swipe command to change pokemon in my script. I'm betting the change to the location data and a retest with your code will resolve that... As it appeared it the code would cycle to the same error as prior with the intent send.

Also... It would be very helpful to have an example of the conditions/actions put in the Yaml Config file but commented out... I.e. a basic, here is what it should look like from a coding standpoint... I've got some experience python and yaml.. but overall i'm fairly new, capable...but still on the noob-side... So.. having an example of how the yaml code should look when performing conditioning/actions would be greatly appreciated... 

Next question.. I am somewhat curious on to how you are doing the appraisal method? I see your sending the same intent to launch Calcy... But is this method going to update it based on the log capture from Calcy or are you going to change the value on silentMode to false and have calcy perform the automatic screen grab? I wonder on this because I'm sure you'll have to call a separate intent in Calcy to get the Appraisal OCR to run... and then i'm betting you would have to pass some type of update along to Calcy to have it perform the IV refinement to get a more updated IV to the be passed back through your logcat capture to perform the rest of the script... I know you can scan the logcat now to for something similar to below capture Calcy's OCR findings but the problem will be the above mentioned refinement, if it can be done silently, and whether or not you have to push the OCR findings to Calcy to get a refined IV after silently running the OCR intention.... or something to that effect.. 

"I/aw      (27260): Appraisal-OCR took 67ms
D/aw      (27260): Appraisal-OCR: Hi caprikcwg  et's take a Iook at your Ocso ng shall wet
D/aw      (27260): Conf. that this is an overall string: 0.246 (after 1ms)
D/aw      (27260): Conf. that this is an 'best stats' string: 0.200 (after 0ms)
D/aw      (27260): Conf. that this is a stats string: 0.226 (after 1ms)
....
I/aw      (27260): Appraisal-OCR took 48ms
D/aw      (27260): Appraisal-OCR: Overall  your Ocso sDWl is a decent Pok├⌐mon.
D/aw      (27260): Conf. that this is an overall string: 0.971 (after 1ms)
D/aw      (27260): Overall (Index 6 => Team Valor, value 3) string: Overall  your Ocso sDWl is a decent Pok├⌐mon.
....
I/aw      (27260): Appraisal-OCR took 23ms
D/aw      (27260): Appraisal-OCR: Its HP is its strongest feature.
D/aw      (27260): Conf. that this is an overall string: 0.180 (after 0ms)
D/aw      (27260): Conf. that this is an 'best stats' string: 1.000 (after 1ms)
D/ba      (27260): Conf. that best stat is 'HP': 1.00 (Its HP is its strongest feature.)
D/aw      (27260): Best stat (Index 2 => Team Valor, value: 2) string: Its HP is its strongest feature.
...
I/aw      (27260): Appraisal-OCR took 28ms
D/aw      (27260): Appraisal-OCR: I'm just as impressed with its Defense.
D/aw      (27260): Conf. that this is an overall string: 0.204 (after 1ms)
D/aw      (27260): Conf. that this is an 'best stats' string: 1.000 (after 0ms)
D/ba      (27260): Conf. that best stat is 'Defense': 1.00 (I'm just as impressed with its Defense.)
D/aw      (27260): Best stat (Index 3 => Team Valor, value: 1) string: I'm just as impressed with its Defense.
....
I/aw      (27260): Appraisal-OCR took 39ms
D/aw      (27260): Appraisal-OCR: Its stats indicate that in battle  it'll get the job done.
D/aw      (27260): Conf. that this is an overall string: 0.281 (after 1ms)
D/aw      (27260): Conf. that this is an 'best stats' string: 0.380 (after 0ms)
D/aw      (27260): Conf. that this is a stats string: 0.983 (after 1ms)
D/aw      (27260): Stats (Index 6 => Team Valor, value 3) string: Its stats indicate that in battle  it'll get the job done."

Also... If i could get clarification to what Appraisal box coordinates you are requesting, it would be appreciated. Is it to the box from Calcy or the "dialog" section from Pokemon Go? 

Apologies to rant... When I was building my script with ADB and Batch.. I unfortunately had to use GoIV because it made it a little easier to grab the screen and had less potential of doing the glitch with Calcy where the press of the button auto launches the appraisal capture menu for some reason but did have an issue with locking up... However, my preference is Calcy and since I'm teaching myself python as it is... this is alls very impressive and enlightening.. I appreciate your tolerance of my rant and inquires.

**Comment by Caprikey** [comment]
Well crap... I forgot to add... When I use the updated adb intention

adb shell am broadcast -a tesmath.calcy.ACTION_ANALYZE_SCREEN -n tesmath.calcy/.IntentReceiver --ez silentMode true

It does appear to be sending correctly on my device... which I verified by adjusting the 'silentMode' to 'False' and the onscreen functionality is there (i.e. It acts like I pressed the button).. So combined with the adjustment to the 'Next' coordinates in the config file and i'm betting it'll run smoothly.... This just leaves the appraisal refinement to further narrow enhance the effectiveness...

Also... What about Egg and Raid adjustment in appraisal? That will become necessary to make sure Appraisals are correct... OCR will work for capturing the statements but how will you handle that? Perhaps a screen swipe to scroll down and the same Screencapture/pixel-color recognition you are doing now? 

I really appreciate all the hard work and I'm trying on my end to learn and contribute if possible... I have a constant struggle with 1500 pokemon in my storage now and I don't want to part with them until i have them all calculated and check... Though... I'm sure with the amount of time I've spent building my own automation tools, learning and building upon yours, and/or looking into ways to do it on device with ADB, Tasker, and an IV tool... I could have just done it all manually by now hahaha

**Comment by Azelphur** [comment]
@Caprikey Phew, long text, ok, here we go.

The code tells calcy to do the scan (which was failing on some devices prior to  4dfa347) and then waits for Calcy IV to return results from a scan. By pressing the button, you were manually doing the part that was failing, calcy iv was outputting results, and things continued on.

The close calcy function closes the Calcy IV dialog that asks for CP / level when a scan fails. By changing the success check you had the script thinking every scan failed, and that it needed to close this Calcy IV dialog.

--touch-paste is needed on devices that don't support the paste keyevent, I have a note 4 here and I know it doesn't support the paste key event. Maybe the S9+ doesn't as well. You can test the paste key by running `adb shell input keyevent 279`

Ideally in the future I want to add per-phone profiles and phone identification to make things easier.

You are correct about swiping, the script taps the area just below the favorite button to advance to the next pokemon, this is quicker than a swipe.

I did actually add some more examples of the yaml actions and conditions to the readme earlier today. Hopefully that covers it.

Appraisals don't care whether silentMode is true or false, they show the calcy dialog and do OCR anyway, my script just taps to advance through the messages, it quickly skips through the first 3, and then essentially does while appraisal_box is mostly white, tap continue_appraisal. So to be clear, no a different intent is not required. I would like to switch to watching for the OCR readouts at some point soon. I wanted something quick and was being lazy with the white box method.

The appraisal_box wants the top left (x, y) and bottom right (x, y) of the message box. I'm going to add some screenshots soon showing what every location wants.

I leave appraisals entirely up to Calcy IV - to my knowledge there's no need to scroll down or check for eggs. Calcy doesn't need that information to detect IVs.

Hope I've covered everything. If not (or if you just wanna chat) feel free to [contact me directly](contact.azelphur.com)

**Comment by calum2255** [comment]
Amazing! Sorry I never got round to replying quick enough! What's the best way to find the numbers needed for the clicks in the YAML file? Everything works for me I just have to manually click to okay the name change.

**Comment by esauvisky** [comment]
> Amazing! Sorry I never got round to replying quick enough! What's the best way to find the numbers needed for the clicks in the YAML file? Everything works for me I just have to manually click to okay the name change.

Go to **Developer Settings** and turn on **Pointer Location**, it'll show a bar on top of your screen with some information about the pointer, the second and third values are your X and Y coordinates (they're labeled as well).
